apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-test
  namespace: default
  labels:
    env: dev
spec:
  selector:
    matchLabels:
      app: django-test-fargate
  template:
    metadata:
      labels:
        app: django-test-fargate
